sudo: required
language: generic
services:
  - docker
before_isntall:
  - echo "start creating an image with dockerfile"
  - docker build -t sunghyeon/docker-react-app Dockerfile.dev .
script:
  - docker run -e CI=true sunghyeon/docker-react-app npm run test -- --coverage
after_success:
  - echo "Test Susccess"