#sudo: required
os: linux

language: generic

dist: Bionic

# docker 환경 구성
services:
  - docker

# Script 를 실행 할수 있는 환경
before_install:
  - echo "start Creating an image with dockfile."
  - docker build -t sunghyeon/docker-react-app -f Dockerfile.dev .

# 실행할 Script(테스트 실행)
script:
  - docker run -e CI=true sunghyeon/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-181225339909"
  bucket_path: "docker-react-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY